---
# tasks file for webservers
- name: Install httpd
  yum: name={{pkg}} state=installed
- name: create index.html
  copy: src=index.html dest=/var/www/html
  notify: restart httpd
- name: start httpd service
  service: name=httpd state=started
